/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author User
 */
public class System_Vista extends javax.swing.JFrame {

    /**
     * Creates new form System_Vista
     */
    public System_Vista() {
        initComponents();
        setSize(930,415);
        setResizable(false); 
        setTitle("Panel de administración");
        setLocationRelativeTo(null); 
        this.repaint(); 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelEmpleados = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelVentas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_Empleados = new javax.swing.JButton();
        btn_Ventas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        IconoEmpresa = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelEmpresa = new javax.swing.JLabel();
        btn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(18, 45, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Empleados");
        jPanelEmpleados.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 10, 70, 15));

        jPanel1.add(jPanelEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, 35));

        jPanelVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ventas");
        jPanelVentas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 10, 70, 15));

        jPanel1.add(jPanelVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 200, 35));

        btn_Empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoEmpleados70x70.png"))); // NOI18N
        jPanel1.add(btn_Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 20, 70, 70));

        btn_Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoVentas70x70.jpg"))); // NOI18N
        jPanel1.add(btn_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 163, 70, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 320));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconoEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoEmpresa100x100.jpg"))); // NOI18N
        jPanel2.add(IconoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 100, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 100));

        jPanel3.setBackground(new java.awt.Color(18, 45, 61));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEmpresa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmpresa.setText("Automóviles del Caribe S. A");
        jPanel3.add(jLabelEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 350, 40));

        btn_Salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Salir.setText("Salir");
        jPanel3.add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 730, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(System_Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(System_Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(System_Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(System_Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new System_Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconoEmpresa;
    private javax.swing.JButton btn_Empleados;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JButton btn_Ventas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEmpresa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelEmpleados;
    private javax.swing.JPanel jPanelVentas;
    // End of variables declaration//GEN-END:variables
}
